import type { Metadata } from 'next';
import './globals.css';
import { JetBrains_Mono, Barlow_Condensed } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-text',
});

const barlow = Barlow_Condensed({
  weight: ['600'],
  variable: '--font-header',
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${jetbrains.variable} ${barlow.variable}`}>
      <body>{children}</body>
    </html>
  );
}
